# Generated by Django 5.1.2 on 2024-10-14 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_ingredient_recipe_recipelink_recipeorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='link',
            field=models.CharField(max_length=200, null=True, verbose_name='레시피 링크'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='dashboard.recipe'),
        ),
        migrations.DeleteModel(
            name='RecipeLink',
        ),
    ]
